name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build application for NanoS, X and S+
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            model: nanos
          - SDK: "$NANOX_SDK"
            model: nanox
          - SDK: "$NANOSP_SDK"
            model: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make TESTING=1 BOLOS_SDK=${{ matrix.SDK }}
          mv bin/app.elf bin/passwords-app-${{ matrix.model }}
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: apps
          path: bin

  job_test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/speculos:latest
      ports:
        - 9999:9999
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: apps
          path: bin
      - name: Run test
        run: |
          pip install --extra-index-url https://test.pypi.org/simple/ -r tests/requirements.txt
          pytest
      - name: Upload Speculos log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: speculos-log
          path: speculos.log

  job_scan_build:
    name: Clang Static Analyzer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make default
      - name: Upload scan result
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build
          path: scan-build
