name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build application for NanoS, X and S+
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            model: nanos
          - SDK: "$NANOX_SDK"
            model: nanox
          - SDK: "$NANOSP_SDK"
            model: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make TESTING=1 BOLOS_SDK=${{ matrix.SDK }}
          mv bin/app.elf bin/passwords-${{ matrix.model }}.elf
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: apps
          path: bin/*elf

  fatstacks_build:
    name: Build application for Fatstacks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone application
        uses: actions/checkout@v3
      - name: Clone SDK
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/ledger-secure-sdk
          path: ./stax-sdk
          ref: fatstacks_1.0.0-rc1
          token: ${{ secrets.STAX_RO }}
      - name: Build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make BOLOS_SDK=./stax-sdk TARGET=fatstacks
          mv bin/app.elf "bin/passwords-fatstacks.elf"
      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: apps
          path: bin/*.elf

  job_test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Download app binary
        uses: actions/download-artifact@v2
        with:
          name: apps
          path: tests/functional/elfs
      - name: Install APT dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Install Python dependencies
        run: pip install --extra-index-url https://test.pypi.org/simple/ -r tests/functional/requirements.txt
      - name: Run test
        run: pytest --tb=short -v tests/functional
      - name: Upload Speculos log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: speculos-log
          path: speculos.log

  job_scan_build:
    name: Clang Static Analyzer
    strategy:
      fail-fast: false
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            model: nanos
          - SDK: "$NANOX_SDK"
            model: nanox
          - SDK: "$NANOSP_SDK"
            model: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs --exclude ${{ matrix.SDK }} make default BOLOS_SDK=${{ matrix.SDK }}
      - name: Upload scan result
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build
          path: scan-build
