name: Build and run functional tests using ragger through reusable workflow

on:
  workflow_dispatch:
    inputs:
      golden_run:
        type: choice
        required: true
        default: 'Raise an error (default)'
        description: CI behavior if the test snapshots are different than expected.
        options:
          - 'Raise an error (default)'
          - 'Open a PR'
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      flags: "use_test"
      upload_app_binaries_artifact: apps

  test:
    name: Run ragger tests using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    needs: build
    with:
      download_app_binaries_artifact: apps
      regenerate_snapshots: ${{ inputs.golden_run == 'Open a PR' }}
