name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'
      - 'tests/*'

jobs:
  check_linting:
    name: Check linting using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: './'
      extensions: 'h,c'

  yamllint:
    name: Check yaml files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yamllint .
