name: Password backup site generation & update

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  generate:
    name: Generate the site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/wui/
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Set Node.js 16.x
        uses: actions/setup-node@v5
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: clients/wui/yarn.lock
      - name: Run install
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
      - name: Upload documentation bundle
        uses: actions/upload-artifact@v6
        with:
          name: site
          path: clients/wui/build/

  deploy:
    name: Deploy the site on GitHub pages
    runs-on: ubuntu-latest
    needs: generate
    if: |
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/master' ||
       github.ref == 'refs/heads/develop' ||
       startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download documentation bundle
        uses: actions/download-artifact@v7
        with:
          name: site
          path: site
      - name: Deploy documentation on pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
