name: Password backup site generation & update

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  generate:
    name: Generate the site
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: clients/wui/
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: clients/wui/
      - name: Upload documentation bundle
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: clients/wui/build/

  deploy:
    name: Deploy the site on Github pages
    runs-on: ubuntu-latest
    needs: generate
    if: |
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/master' ||
       github.ref == 'refs/heads/develop' ||
       startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download documentation bundle
        uses: actions/download-artifact@v4
      - name: Deploy documentation on pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
